# See https://pnpm.io/workspaces for more information
packages:
  - '.'

# Configurações do pnpm
auto-install-peers: true
strict-peer-dependencies: false
save-exact: true
prefer-workspace-packages: true

# Configurações de cache
store-dir: .pnpm-store
cache-dir: .pnpm-cache

# Configurações de segurança
audit-level: moderate
fund: false
